const constant = {
	ADD_ERROR: "ADD_ERROR",
	ADD_USER: "ADD_USER",
	REMOVE_USER: "REMOVE_USER",
	UPDATE_USER: "UPDATE_USER",
	ADD_ACCESS_TOKEN: "ADD_ACCESS_TOKEN",
	REMOVE_ACCESS_TOKEN: "REMOVE_ACCESS_TOKEN",
};

export default constant;